### ISSUE TITLE
Recommended documentation update to include minimum nodeJS version

### ISSUE THREAD

**Issue by jflowers45** [mike-north/sass-workshop#4]
Thanks for teaching this great course - I caught it on frontendmasters

I had node an installation of nodeJS from the pre io.js days that failed, so I upgraded to 5.0 (which is the default that comes with homebrew) which gave me the following error.
**"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"**

Next I installed 6.11 and it worked fine.  So, just a recommendation that somewhere in the docs you note the min version.

**Comment by jflowers45** [comment]
I hadn't realized this gist was linked from the player on frontendmasters - but it might be worth linking from this repo 

https://gist.github.com/1Marc/ccc99b341da3362a97dd9b3d06b67902

**Comment by mike-north** [comment]
Thanks for pointing this out! I've added it directly to the README so people don't have to find or follow a link. Commit: https://github.com/mike-north/sass-workshop/commit/5b0aae352186d627c6f05a87772de82e494a390a
