### ISSUE TITLE
./run -e nesting command not working in windows command prompt/node command prompt

### ISSUE THREAD

**Issue by KarimaYua** [mike-north/sass-workshop#5]
I'm trying to follow along for the exercises on front end masters, but the ./run /run or run command doesn't get recognised and gives me this error:

'run' is not recognized as an internal or external command,
operable program or batch file.

I don't know how to fix this, or what other command I can use. (I have node.js installed and up to date)

**Comment by mike-north** [comment]
The `run` script is intended to be run in an environment that supports bash. Are you using windows 10?

**Comment by mike-north** [comment]
Workaround until I clean a few things up:
`node run -e nesting`

**Comment by mike-north** [comment]
Nevermind. Workaround should no longer be required :)
